In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

RUNNER_NAME = 'Canya Molly'

formatted_name = RUNNER_NAME.lower().replace(' ', '-')

url = f'https://www.thegreyhoundrecorder.com.au/greyhounds/{formatted_name}/'

headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
tables = pd.read_html(url, storage_options=headers)

races = tables[2]

times_312m = races[races['Dist'] == 312]
times_383m = races[races['Dist'] == 383]

# plot a histogram for 312m times
plt.hist(times_312m['Time'], bins=4)
plt.hist(times_383m['Time'], bins=4, color='orange')
plt.title(f'{RUNNER_NAME} times for 312m races')
plt.xlabel('Time (seconds)')
plt.ylabel('Frequency')
plt.grid(axis='y', alpha=0.75)
plt.show()

Table 1:

,Date,Track,Race Number & Name,Grade,Dist,Rug,Field & Form
0,25-Jan-26,Darwin,R3 - Btc Constructions Dash Division1,X34,383,NaN,Fields | Form

Table 2:

   Starts  Wins  2nd  3rd Prizemoney Win %
0      34    11    6    6    $15,065   32%

Table 3:

,Date,Track,Fin,Box,Dist,Grade,Time,BON,Time Adj,New T,Trk Rtg,Marg,PIR,Winner / 2nd,SP
0,18/01/26,DAR,5th,NaN,312,X34,18.79,18.29,-0.15,18.64,Par,7.00,NaN,Zelda Chaos,$7.00
1,14/01/26,DAR,4th,NaN,383,X45,22.84,21.84,0.09,22.93,Par,9.25,NaN,Brittain On Fire,$5.40
2,11/01/26,DAR,6th,NaN,312,X12,18.90,17.94,0.17,19.07,Fast,13.75,NaN,Brittain On Fire,$12.80
3,04/01/26,DAR,6th,NaN,312,O,18.77,18.08,-0.03,18.74,Par,9.25,NaN,Bantam Magic,$17.60
4,21/12/25,DAR,1st,NaN,383,5,22.51,22.40,-0.20,22.31,Slow,1.50,1.0,Lucy's Chance,$4.20

    Dist   Time
0    312  18.79
1    383  22.84
2    312  18.90
3    312  18.77
4    383  22.51
5    383  22.54
6    312  18.33
7    312  18.56
8    383  22.77
9    383  23.74
10   383  22.85
11   383  22.82
12   383  22.45
13   383  22.64
14   383  22.39
15   312  18.19
16   383  22.98
17   312  18.21
18   383  22.48
19   312  18.31
20   383  22.41
21   383  22.75
22   383  22.42
23   312  18.42
24   312  18.14
25   312  18.42
26   383  22.41
27   383  22.52
28   383  22.42
29   383  22.22
30   312  18.20
31   383  22.77
32   312  18.09
33   312  18.02
Table 4:

   Starts  Wins  2nd  3rd Prizemoney Win %
0      34    11    6    6    $15,065   32%

Table 5:

   Box  Runs  Wins  2nds  3rds Win%
0  NaN     2     1     1     0  50%
1  NaN    13     5     1     4  38%
2  NaN     0     0     0     0   0%
3  NaN     7     2     1     0  29%
4  NaN     1     0     1     0   0%

Table 6:

  Years  Runners  Starts  Wins  2nds  3rds      P/Money    W %    P %
0  2017    286.0    2798   658   424   401   $1,783,354  23.5%  53.0%
1  2018    644.0   14248  2869  2347  2009  $12,245,461  20.1%  50.7%
2  2019   1067.0   19005  3377  3054  2667  $12,593,756  17.8%  47.9%
3  2020   2234.0   40806  7703  6529  5721  $23,522,821  18.9%  48.9%
4  2021   2764.0   56880  9277  8750  8146  $32,916,674  16.3%  46.0%

Table 7:

     Distance  Runners  Starts   Wins   2nds   3rds      P/Money    W %    P %
0  Up to 400m  15158.0  163257  25719  24291  22883  $56,125,155  15.8%  44.6%
1  401 - 500m  11406.0   82153  12971  12488  11463  $39,293,920  15.8%  44.9%
2  501 - 600m   9219.0   89260  14988  13998  12813  $99,184,703  16.8%  46.8%
3  601 - 700m   1190.0    4003    756    678    612   $4,590,511  18.9%  51.1%
4   Over 700m    662.0    3827    713    697    638  $10,654,039  18.6%  53.5%

Table 8:

    Years  Runners  Starts  Wins  2nds  3rds  P/Money    W %    P %
0    2025      2.0      53    18     9    10  $33,395  34.0%  69.8%
1    2026      2.0       7     1     0     0   $1,770  14.3%  14.3%
2  Totals      NaN      60    19     9    10  $35,165  31.7%  63.3%

Table 9:

     Distance  Runners  Starts  Wins  2nds  3rds  P/Money    W %    P %
0  Up to 400m      4.0      44    15     8     7  $21,885  34.1%  68.2%
1  501 - 600m      1.0      16     4     1     3  $13,280  25.0%  50.0%
2      Totals      NaN      60    19     9    10  $35,165  31.7%  63.3%

Table 10:

,Dog Name,Starts,Wins,2nd,3rd,Prize Money,Win %,Dam,Whelp Date
0,No progeny recorded for this greyhound,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Table 11:

            Name  Starts  Wins  2nd  3rd Prizemoney  Win %
0    Canya Molly      34    11    6    6    $15,065  32.4%
1  Canya Talking      24     8    3    4    $20,100  33.3%
2         Totals      58    19    9   10    $35,165  32.8%