In [1]:
import pandas as pd
import numpy as np

marketdata = pd.read_csv('bush-bro_blazin-bulla.csv')
names_set = set(marketdata['selection_md.name'])

# Gets the average back and lay odds
race_length = int(input("Please input the race distance: "))
race_date = str(marketdata.tail(1)['publishTime']).split()[1]

runner_names = []

for name in names_set:
    runner_name = name.split('.')[1].strip()
    runner_names.append(runner_name)
    records = marketdata[marketdata['selection_md.name'] == name]
    back_mean = records['selection_ex.availableToBack.price'].tail(15).mean()
    lay_mean = records['selection_ex.availableToLay.price'].tail(15).mean()

    print(f"{runner_name}: BACK ${back_mean:.2f} | LAY ${lay_mean:.2f}")
    #display(records.tail(15))

Blazin Bulla: BACK $2.08 | LAY $2.18
Bush Bro: BACK $1.85 | LAY $1.92

In [ ]:
import main

runner1_name, runner2_name = runner_names[0], runner_names[1]

table1 = main.read_greyhound_data(runner1_name, race_length, race_date)
table2 = main.read_greyhound_data(runner2_name, race_length, race_date)

#display(table1)
#display(table2)

if table1.shape[0] == 0 or table2.shape[0] == 0:
    print("ERROR: Unable to retrieve data for one or both greyhounds.")
    exit(1)
else:
    runner1_params = main.fit_normal_dist(table1)
    runner2_params = main.fit_normal_dist(table2)

    prob_runner1, prob_runner2 = main.simulate(runner1_params, runner2_params)
    fair_odds1 = 1 / prob_runner1 if prob_runner1 != 0 else None
    fair_odds2 = 1 / prob_runner2 if prob_runner2 != 0 else None

    print(f"\n-----RESULTS-----")

    print(f"{runner1_name}:")
    print(f"\tFair odds    : {fair_odds1:.2f}")
    print(f"\tWin %        : {100*prob_runner1:.2f}")
    print(f"\tNo. samples  : {len(table1)}")

    print(f"{runner2_name}:")
    print(f"\tFair odds    : {fair_odds2:.2f}")
    print(f"\tWin %        : {100*prob_runner2:.2f}")
    print(f"\tNo. samples  : {len(table2)}")

# update

,Date,Track,Fin,Box,Dist,Grade,Time,BON,Time Adj,New T,Trk Rtg,Marg,PIR,Winner / 2nd,SP
4,08/08/20,SHP,6th,NaN,450,T3-5,26.37,25.83,-0.19,26.18,Slow,5.63,M/567,Jetta's Shout,$13.00
7,25/07/20,SHP,6th,NaN,450,5,25.84,24.98,0.15,25.99,Par,12.29,M/676,Popcorn Payout,$61.00
9,13/07/20,SHP,5th,NaN,450,T3-5,26.11,25.70,-0.02,26.09,Par,4.81,M/766,Alfie Mikado,$6.50
10,06/07/20,SHP,7th,NaN,450,T3-5,26.11,25.59,0.04,26.15,Par,7.51,M/667,Jetta's Shout,$21.00
11,29/06/20,SHP,2nd,NaN,450,T3-5,25.91,25.74,0.01,25.92,Par,2.40,M/432,Star Catcher,$8.50
15,28/05/20,SHP,6th,NaN,450,VET,25.99,24.99,0.12,26.11,Par,6.01,M/344,Manitoba,$15.00
16,25/05/20,SHP,2nd,NaN,450,T3-5,25.74,25.66,-0.01,25.73,Par,1.19,Q/111,Aston Squire,$41.00
19,04/05/20,SHP,7th,NaN,450,T3-5,26.05,25.41,0.07,26.12,Par,9.10,M/776,Hardaway Jayjay,$17.00
20,27/04/20,SHP,3rd,NaN,450,T3-5,26.15,25.64,-0.06,26.09,Par,2.96,M/212,Gigi's Fire,$8.50
36,23/12/19,SHP,7th,NaN,450,T3-5,26.14,25.46,0.09,26.23,Par,9.77,M/345,Speckie Mckean,$17.00
43,28/10/19,SHP,6th,NaN,450,5H,26.13,25.05,0.05,26.18,Par,8.86,M/356,Head Banger,$0.00
51,08/08/19,SHP,6th,NaN,450,RWH,25.99,25.44,-0.19,25.80,Slow,7.79,M/677,Dolly Mac,$34.00
79,07/01/19,SHP,7th,NaN,450,T3-6,26.13,25.40,0.02,26.15,Par,10.39,M/113,Liberal Nunnio,$7.50
83,03/11/18,SHP,2nd,NaN,450,X67,25.81,24.96,-0.01,25.80,Par,0.46,M/232,Mogo Jet,$41.00
85,22/10/18,SHP,7th,NaN,450,7,26.52,25.57,0.06,26.58,Par,8.87,M/234,Aqualite,$3.75
91,16/07/18,BAL,7th,NaN,450,T3-7,26.60,26.05,-0.18,26.42,Slow,7.23,M/455,Spritely Brew,$26.00

,Date,Track,Fin,Box,Dist,Grade,Time,BON,Time Adj,New T,Trk Rtg,Marg,PIR,Winner / 2nd,SP
0,19/10/20,BAL,6th,NaN,450,T3-5,26.37,25.50,0.13,26.50,Par,8.71,M/467,Bush Tiger,$51.00
1,14/10/20,SHP,6th,NaN,450,T3-5,26.17,25.47,-0.05,26.12,Par,8.25,M/666,Cobber Victorem,$17.00
5,13/08/20,SHP,5th,NaN,450,T3-5,26.23,25.41,-0.08,26.15,Par,7.87,M/433,East Street,$31.00
6,08/08/20,SHP,4th,NaN,450,T3-5,26.30,25.83,-0.19,26.11,Slow,4.61,M/222,Jetta's Shout,$34.00
8,25/07/20,SHP,8th,NaN,450,5,26.39,24.98,0.15,26.54,Par,14.23,M/867,Volcanic Lava,$31.00
9,20/07/20,SHP,1st,NaN,450,T3-5,25.70,25.58,0.01,25.71,Par,0.81,M/321,Secret Chimp,$8.50
11,13/07/20,SHP,2nd,NaN,450,T3-5,25.92,25.70,-0.02,25.90,Par,0.71,M/222,Secret Thoughts,$31.00
13,29/06/20,SHP,4th,NaN,450,T3-5,25.95,25.74,0.01,25.96,Par,2.94,M/635,Secret Chimp,$31.00
22,04/05/20,SHP,8th,NaN,450,T3-5,26.28,25.41,0.07,26.35,Par,12.43,M/888,Hardaway Jayjay,$17.00
23,27/04/20,SHP,5th,NaN,450,T3-5,26.25,25.64,-0.06,26.19,Par,4.41,M/344,Gigi's Fire,$7.50
24,20/04/20,SHP,1st,NaN,450,T3-5,25.98,25.77,-0.19,25.79,Slow,2.61,M/211,Panel,$6.00
26,13/04/20,SHP,3rd,NaN,450,T3-5,26.42,25.98,-0.34,26.08,Slow,6.25,M/222,Northern Zone,$17.00
49,05/09/19,WBL,8th,NaN,450,RW,26.48,25.04,-0.05,26.43,Par,15.21,M/454,Giggling Gerty,$34.00
66,31/01/19,WBL,4th,NaN,450,M,26.25,25.13,-0.08,26.17,Par,11.44,M/432,Saluted,$41.00

-----RESULTS-----
Blazin Bulla:
	Fair odds    : 1.62
	Win %        : 61.62
	No. samples  : 16
Bush Bro:
	Fair odds    : 2.61
	Win %        : 38.38
	No. samples  : 14