In [11]:
import pandas as pd
import numpy as np

marketdata = pd.read_csv('springvale-misty_sweet-potato.csv')
names_set = set(marketdata['selection_md.name'])

# Gets the average back and lay odds
race_length = int(input("Please input the race distance: "))
race_date = str(marketdata.tail(1)['publishTime']).split()[1]

runner_names = []

for name in names_set:
    runner_name = name.split('.')[1].strip()
    runner_names.append(runner_name)
    records = marketdata[marketdata['selection_md.name'] == name]
    back_mean = records['selection_ex.availableToBack.price'].tail(15).mean()
    lay_mean = records['selection_ex.availableToLay.price'].tail(15).mean()

    print(f"{runner_name}: BACK ${back_mean:.2f} | LAY ${lay_mean:.2f}")
    display(records.tail(15))

Sweet Potato: BACK $1.63 | LAY $1.84

,publishTime,totalMatched,md.eventName,md.name,marketId,betDelay,bspReconciled,complete,status,runnersVoidable,...,selection_ex.availableToLay.size,selection_status,selection_md.name,selection_handicap,selection_totalMatched,selection_adjustmentFactor,selection_removalDate,selection_sp.actualSP,selection_sp.nearPrice,selection_sp.farPrice
237,2020-05-04 05:57:53.379000,58.34,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,OPEN,False,...,10.83,ACTIVE,3. Sweet Potato,0,37.79,NaN,NaN,NaN,NaN,NaN
239,2020-05-04 05:57:55.283000,80.72,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,OPEN,False,...,10.83,ACTIVE,3. Sweet Potato,0,37.86,NaN,NaN,NaN,NaN,NaN
241,2020-05-04 05:57:56.623000,80.72,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,OPEN,False,...,10.83,ACTIVE,3. Sweet Potato,0,37.86,NaN,NaN,NaN,NaN,NaN
243,2020-05-04 05:58:00.514000,80.77,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,OPEN,False,...,10.83,ACTIVE,3. Sweet Potato,0,37.89,NaN,NaN,NaN,NaN,NaN
245,2020-05-04 05:58:01.913000,120.77,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,OPEN,False,...,10.83,ACTIVE,3. Sweet Potato,0,77.89,NaN,NaN,NaN,NaN,NaN
246,2020-05-04 05:58:04.431000,120.77,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,OPEN,False,...,10.83,ACTIVE,3. Sweet Potato,0,77.89,NaN,NaN,NaN,NaN,NaN
247,2020-05-04 05:58:06.338000,120.77,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,OPEN,False,...,10.83,ACTIVE,3. Sweet Potato,0,77.89,NaN,NaN,NaN,NaN,NaN
248,2020-05-04 05:58:29.550000,120.77,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,OPEN,False,...,2.56,ACTIVE,3. Sweet Potato,0,77.89,NaN,NaN,NaN,NaN,NaN
249,2020-05-04 05:58:30.069000,120.77,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,OPEN,False,...,2.56,ACTIVE,3. Sweet Potato,0,77.89,NaN,NaN,NaN,NaN,NaN
252,2020-05-04 05:58:50.094000,159.02,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,OPEN,False,...,4.57,ACTIVE,3. Sweet Potato,0,98.99,NaN,NaN,NaN,NaN,NaN
254,2020-05-04 05:58:52.235000,159.02,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,SUSPENDED,False,...,4.57,ACTIVE,3. Sweet Potato,0,98.99,NaN,NaN,NaN,NaN,NaN
256,2020-05-04 05:58:52.275000,159.02,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,SUSPENDED,False,...,NaN,ACTIVE,3. Sweet Potato,0,98.99,NaN,NaN,NaN,NaN,NaN
258,2020-05-04 06:03:26.095000,158.90,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,SUSPENDED,False,...,NaN,ACTIVE,3. Sweet Potato,0,98.95,NaN,NaN,NaN,NaN,NaN
260,2020-05-04 06:03:26.696000,0.00,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,SUSPENDED,False,...,NaN,ACTIVE,3. Sweet Potato,0,0.00,NaN,NaN,NaN,NaN,NaN
262,2020-05-04 06:03:27.597000,0.00,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,CLOSED,False,...,NaN,LOSER,3. Sweet Potato,0,0.00,NaN,NaN,NaN,NaN,NaN

Springvale Misty: BACK $2.18 | LAY $8.29

,publishTime,totalMatched,md.eventName,md.name,marketId,betDelay,bspReconciled,complete,status,runnersVoidable,...,selection_ex.availableToLay.size,selection_status,selection_md.name,selection_handicap,selection_totalMatched,selection_adjustmentFactor,selection_removalDate,selection_sp.actualSP,selection_sp.nearPrice,selection_sp.farPrice
232,2020-05-04 05:57:38.670000,58.34,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,OPEN,False,...,6.77,ACTIVE,1. Springvale Misty,0,20.55,NaN,NaN,NaN,NaN,NaN
234,2020-05-04 05:57:40.264000,58.34,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,OPEN,False,...,6.77,ACTIVE,1. Springvale Misty,0,20.55,NaN,NaN,NaN,NaN,NaN
235,2020-05-04 05:57:45.407000,58.34,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,OPEN,False,...,6.77,ACTIVE,1. Springvale Misty,0,20.55,NaN,NaN,NaN,NaN,NaN
236,2020-05-04 05:57:52.401000,58.34,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,OPEN,False,...,61.00,ACTIVE,1. Springvale Misty,0,20.55,NaN,NaN,NaN,NaN,NaN
238,2020-05-04 05:57:55.283000,80.72,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,OPEN,False,...,61.00,ACTIVE,1. Springvale Misty,0,42.86,NaN,NaN,NaN,NaN,NaN
240,2020-05-04 05:57:56.008000,80.72,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,OPEN,False,...,0.01,ACTIVE,1. Springvale Misty,0,42.86,NaN,NaN,NaN,NaN,NaN
242,2020-05-04 05:58:00.514000,80.77,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,OPEN,False,...,61.00,ACTIVE,1. Springvale Misty,0,42.88,NaN,NaN,NaN,NaN,NaN
244,2020-05-04 05:58:01.913000,120.77,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,OPEN,False,...,61.00,ACTIVE,1. Springvale Misty,0,42.88,NaN,NaN,NaN,NaN,NaN
250,2020-05-04 05:58:47.198000,120.77,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,OPEN,False,...,16.95,ACTIVE,1. Springvale Misty,0,42.88,NaN,NaN,NaN,NaN,NaN
251,2020-05-04 05:58:50.094000,159.02,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,OPEN,False,...,61.00,ACTIVE,1. Springvale Misty,0,60.03,NaN,NaN,NaN,NaN,NaN
253,2020-05-04 05:58:52.235000,159.02,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,SUSPENDED,False,...,61.00,ACTIVE,1. Springvale Misty,0,60.03,NaN,NaN,NaN,NaN,NaN
255,2020-05-04 05:58:52.275000,159.02,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,SUSPENDED,False,...,NaN,ACTIVE,1. Springvale Misty,0,60.03,NaN,NaN,NaN,NaN,NaN
257,2020-05-04 06:03:26.095000,158.90,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,SUSPENDED,False,...,NaN,ACTIVE,1. Springvale Misty,0,59.95,NaN,NaN,NaN,NaN,NaN
259,2020-05-04 06:03:26.696000,0.00,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,SUSPENDED,False,...,NaN,ACTIVE,1. Springvale Misty,0,0.00,NaN,NaN,NaN,NaN,NaN
261,2020-05-04 06:03:27.597000,0.00,Shep (AUS) 4th May,Springvale Misty v Sweet Potato,1.170375,0,False,True,CLOSED,False,...,NaN,WINNER,1. Springvale Misty,0,0.00,NaN,NaN,NaN,NaN,NaN

In [12]:
import main

runner1_name, runner2_name = runner_names[0], runner_names[1]

table1 = main.read_greyhound_data(runner1_name, race_length, race_date)
table2 = main.read_greyhound_data(runner2_name, race_length, race_date)

if table1.shape[0] == 0 or table2.shape[0] == 0:
    print("ERROR: Unable to retrieve data for one or both greyhounds.")
    exit(1)
else:
    runner1_params = main.fit_normal_dist(table1)
    runner2_params = main.fit_normal_dist(table2)

    prob_runner1, prob_runner2 = main.simulate(runner1_params, runner2_params)
    fair_odds1 = 1 / prob_runner1 if prob_runner1 != 0 else None
    fair_odds2 = 1 / prob_runner2 if prob_runner2 != 0 else None

    print(f"\n-----RESULTS-----")

    print(f"{runner1_name}:")
    print(f"\tFair odds    : {fair_odds1:.2f}")
    print(f"\tWin %        : {100*prob_runner1:.2f}")
    print(f"\tNo. samples  : {len(table1)}")

    print(f"{runner2_name}:")
    print(f"\tFair odds    : {fair_odds2:.2f}")
    print(f"\tWin %        : {100*prob_runner2:.2f}")
    print(f"\tNo. samples  : {len(table2)}")

# update

WARNING: less than 5 found!
ERROR: Unable to retrieve data for one or both greyhounds.