In [ ]:
import pandas as pd
import numpy as np

marketdata = pd.read_csv('marketdata.csv')
names_set = set(marketdata['selection_md.name'])

#Gets the average back and lay odds
runner_names = []
for name in names_set:
    split = name.split('.',)
    runner_name = split[1]
    runner_names.append(runner_name)
    records = marketdata[marketdata['selection_md.name'] == name]
    back_mean = records['selection_ex.availableToBack.price'].tail(15).mean()
    lay_mean = records['selection_ex.availableToLay.price'].tail(15).mean()
    print(back_mean,lay_mean)
    display(records.tail(15))
distance = input("Please input the race distance: ")
runner_names.append(distance)
avb_details = tuple(runner_names)

2.083333333333333 2.1783333333333332

,publishTime,totalMatched,selection_selectionId,selection_lastPriceTraded,selection_ex.availableToBack.price,selection_ex.availableToBack.size,selection_ex.availableToLay.price,selection_ex.availableToLay.size,selection_status,selection_md.name,selection_handicap,selection_totalMatched,selection_adjustmentFactor,selection_removalDate,selection_sp.actualSP,selection_sp.nearPrice,selection_sp.farPrice
377,2020-05-04 07:21:18.636000,1114.32,18937450,2.10,2.08,26.29,2.14,12.16,ACTIVE,3. Blazin Bulla,0,522.30,NaN,NaN,NaN,NaN,NaN
379,2020-05-04 07:21:19.518000,1176.29,18937450,2.08,2.06,16.58,2.14,12.16,ACTIVE,3. Blazin Bulla,0,579.38,NaN,NaN,NaN,NaN,NaN
380,2020-05-04 07:21:20.185000,1176.29,18937450,2.08,2.04,24.88,2.14,12.16,ACTIVE,3. Blazin Bulla,0,579.38,NaN,NaN,NaN,NaN,NaN
381,2020-05-04 07:21:21.830000,1176.29,18937450,2.08,2.06,72.82,2.14,12.16,ACTIVE,3. Blazin Bulla,0,579.38,NaN,NaN,NaN,NaN,NaN
383,2020-05-04 07:21:22.709000,1200.65,18937450,2.14,2.14,0.13,2.18,24.14,ACTIVE,3. Blazin Bulla,0,603.74,NaN,NaN,NaN,NaN,NaN
384,2020-05-04 07:21:23.588000,1200.65,18937450,2.14,2.14,0.13,2.20,37.71,ACTIVE,3. Blazin Bulla,0,603.74,NaN,NaN,NaN,NaN,NaN
385,2020-05-04 07:21:26.022000,1200.65,18937450,2.14,2.14,0.13,2.20,14.00,ACTIVE,3. Blazin Bulla,0,603.74,NaN,NaN,NaN,NaN,NaN
387,2020-05-04 07:21:26.538000,1202.22,18937450,2.14,2.06,89.41,2.20,14.00,ACTIVE,3. Blazin Bulla,0,603.87,NaN,NaN,NaN,NaN,NaN
389,2020-05-04 07:21:27.210000,1202.42,18937450,2.06,2.06,116.13,2.20,14.00,ACTIVE,3. Blazin Bulla,0,604.07,NaN,NaN,NaN,NaN,NaN
391,2020-05-04 07:21:28.400000,1217.76,18937450,2.06,2.06,116.13,2.20,14.00,ACTIVE,3. Blazin Bulla,0,604.07,NaN,NaN,NaN,NaN,NaN
393,2020-05-04 07:21:30.106000,1222.42,18937450,2.06,2.06,43.40,2.20,14.00,ACTIVE,3. Blazin Bulla,0,604.07,NaN,NaN,NaN,NaN,NaN
394,2020-05-04 07:21:30.624000,1222.42,18937450,2.06,2.10,72.72,2.20,14.00,ACTIVE,3. Blazin Bulla,0,604.07,NaN,NaN,NaN,NaN,NaN
396,2020-05-04 07:21:31.400000,1222.42,18937450,2.06,NaN,NaN,NaN,NaN,ACTIVE,3. Blazin Bulla,0,604.07,NaN,NaN,NaN,NaN,NaN
398,2020-05-04 07:25:50.832000,0.00,18937450,2.02,NaN,NaN,NaN,NaN,ACTIVE,3. Blazin Bulla,0,0.00,NaN,NaN,NaN,NaN,NaN
400,2020-05-04 07:25:51.688000,0.00,18937450,2.02,NaN,NaN,NaN,NaN,WINNER,3. Blazin Bulla,0,0.00,NaN,NaN,NaN,NaN,NaN

1.8475000000000001 1.9183333333333337

,publishTime,totalMatched,selection_selectionId,selection_lastPriceTraded,selection_ex.availableToBack.price,selection_ex.availableToBack.size,selection_ex.availableToLay.price,selection_ex.availableToLay.size,selection_status,selection_md.name,selection_handicap,selection_totalMatched,selection_adjustmentFactor,selection_removalDate,selection_sp.actualSP,selection_sp.nearPrice,selection_sp.farPrice
363,2020-05-04 07:21:03.171000,1029.29,26859492,1.91,1.84,25.92,1.91,5.47,ACTIVE,1. Bush Bro,0,549.48,NaN,NaN,NaN,NaN,NaN
364,2020-05-04 07:21:05.918000,1029.29,26859492,1.91,1.84,5.00,1.91,5.47,ACTIVE,1. Bush Bro,0,549.48,NaN,NaN,NaN,NaN,NaN
366,2020-05-04 07:21:06.693000,1033.29,26859492,1.91,1.84,5.00,1.91,5.47,ACTIVE,1. Bush Bro,0,549.48,NaN,NaN,NaN,NaN,NaN
369,2020-05-04 07:21:09.215000,1033.29,26859492,1.91,1.84,5.00,1.90,50.80,ACTIVE,1. Bush Bro,0,549.48,NaN,NaN,NaN,NaN,NaN
371,2020-05-04 07:21:11.892000,1114.32,26859492,1.90,1.84,5.00,1.90,8.26,ACTIVE,1. Bush Bro,0,592.02,NaN,NaN,NaN,NaN,NaN
376,2020-05-04 07:21:17.705000,1114.32,26859492,1.90,1.84,5.00,1.91,5.47,ACTIVE,1. Bush Bro,0,592.02,NaN,NaN,NaN,NaN,NaN
378,2020-05-04 07:21:19.518000,1176.29,26859492,1.91,1.84,5.00,1.91,0.58,ACTIVE,1. Bush Bro,0,596.91,NaN,NaN,NaN,NaN,NaN
382,2020-05-04 07:21:22.709000,1200.65,26859492,1.91,1.84,5.00,1.91,0.58,ACTIVE,1. Bush Bro,0,596.91,NaN,NaN,NaN,NaN,NaN
386,2020-05-04 07:21:26.538000,1202.22,26859492,1.94,1.84,5.00,1.94,9.78,ACTIVE,1. Bush Bro,0,598.35,NaN,NaN,NaN,NaN,NaN
388,2020-05-04 07:21:27.210000,1202.42,26859492,1.94,1.84,5.00,1.94,9.78,ACTIVE,1. Bush Bro,0,598.35,NaN,NaN,NaN,NaN,NaN
390,2020-05-04 07:21:28.400000,1217.76,26859492,1.93,1.93,2.33,1.94,9.78,ACTIVE,1. Bush Bro,0,613.69,NaN,NaN,NaN,NaN,NaN
392,2020-05-04 07:21:30.106000,1222.42,26859492,1.93,1.84,5.00,1.94,9.78,ACTIVE,1. Bush Bro,0,618.35,NaN,NaN,NaN,NaN,NaN
395,2020-05-04 07:21:31.400000,1222.42,26859492,1.93,NaN,NaN,NaN,NaN,ACTIVE,1. Bush Bro,0,618.35,NaN,NaN,NaN,NaN,NaN
397,2020-05-04 07:25:50.832000,0.00,26859492,1.82,NaN,NaN,NaN,NaN,ACTIVE,1. Bush Bro,0,0.00,NaN,NaN,NaN,NaN,NaN
399,2020-05-04 07:25:51.688000,0.00,26859492,1.82,NaN,NaN,NaN,NaN,LOSER,1. Bush Bro,0,0.00,NaN,NaN,NaN,NaN,NaN

In [ ]:
import main

runner1_name, runner2_name, race_length = avb_details

table1 = main.read_greyhound_data(runner1_name)
table2 = main.read_greyhound_data(runner2_name)

if table1 is None or table2 is None:
    print("ERROR: Unable to retrieve data for one or both greyhounds.")
    exit(1)
else:
    runner1_params = main.fit_normal_dist(table1, race_length)
    runner2_params = main.fit_normal_dist(table2, race_length)

    prob_runner1, prob_runner2 = main.simulate(runner1_params, runner2_params)
    fair_odds1 = 1 / prob_runner1 if prob_runner1 != 0 else None
    fair_odds2 = 1 / prob_runner2 if prob_runner2 != 0 else None

    print(f"\n-----RESULTS-----")

    print(f"{runner1_name}:")
    print(f"\tFair odds    : {fair_odds1:.2f}")
    print(f"\tWin %        : {prob_runner1:.2f}")
    print(f"\tNo. samples  : {len(table1)}")

    print(f"{runner2_name}:")
    print(f"\tFair odds    : {fair_odds2:.2f}")
    print(f"\tWin %        : {prob_runner2:.2f}")
    print(f"\tNo. samples  : {len(table2)}")

HTTPError: HTTP Error 404: Not Found